In [3]:
#建立list
a = [1, 3, 5, 7, 9]
a * 2

b = [2, 4, 6, 8 ,10]
a + b

result = []
for i in range(5):
    result.append(a[i] + b[i])

result

[3, 7, 11, 15, 19]

In [8]:
import numpy as np

#透過list建立ndArray

a_array = np.array([1, 3, 5, 7, 9])
a_array * 2

b_array = np.array([2, 4, 6, 8 ,10])

a_array + b_array

array([ 3,  7, 11, 15, 19])

In [10]:
#使用python建立5個亂數元素的list
import random

#list comprehension
[random.randint(50,100) for _ in range(5)]


[95, 57, 97, 60, 51]

In [11]:
#使用numpy random 建立亂數
import numpy as np
np.random.randint(50,high=100,size=5)

array([93, 99, 50, 65, 76])

In [12]:
np.random.randint(50,high=100,size=(50, 5))

array([[80, 96, 88, 84, 83],
       [99, 66, 72, 68, 84],
       [69, 92, 60, 51, 91],
       [80, 95, 50, 55, 53],
       [92, 85, 88, 79, 65],
       [97, 80, 85, 90, 82],
       [91, 71, 96, 52, 80],
       [88, 60, 99, 96, 61],
       [88, 61, 78, 69, 97],
       [80, 62, 90, 61, 68],
       [97, 73, 81, 51, 64],
       [96, 88, 52, 54, 52],
       [68, 85, 89, 59, 74],
       [53, 65, 98, 52, 84],
       [54, 75, 79, 99, 51],
       [98, 85, 67, 91, 80],
       [92, 72, 96, 84, 74],
       [82, 64, 95, 75, 67],
       [78, 86, 96, 64, 81],
       [70, 66, 59, 92, 87],
       [61, 80, 89, 56, 92],
       [96, 87, 86, 59, 73],
       [96, 89, 54, 78, 72],
       [92, 60, 63, 61, 55],
       [58, 72, 78, 90, 64],
       [70, 97, 80, 56, 79],
       [59, 52, 54, 57, 92],
       [92, 95, 51, 73, 85],
       [69, 84, 94, 72, 98],
       [75, 77, 64, 99, 88],
       [90, 53, 76, 92, 79],
       [80, 74, 68, 68, 68],
       [66, 90, 72, 81, 63],
       [79, 81, 91, 92, 95],
       [52, 98